What does Pandas stand for?

    - Panel Data

What are the 2 collections used in Pandas?

    - Series and DataFrame

Name 4 things Pandas can do for us.

    - Data cleansing, data normailization, data visualization, data inspection

To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

    - inplace= True

What is a CSV

    - Stands for Comma Seperated Values.  It is a plain text file that allows data to be saved in a tabular format

When cleaning data what values do we not like in our data?

    - Null

In [3]:
import numpy as np

# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()

twoThreeTwoArray = np.array[
        [[1,2], [3,4] , [5,6]],
        [[7,8], [9,10], [11, 12]]


]

print(twoThreeTwoArray)

#not sure if I needed to create an array with a shape of (2,3,2) and then reshape it?  What would I reshape it into?

# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

spacedArray = np.linspace(0, 20, num=6)
print(spacedArray)


# 9. Make a Deep Copy of the above array
import copy

spacedArray[0] = 12
deepArray = spacedArray.copy()


print(deepArray)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [143]:
import numpy as np
# 11. Concatenate these 3 arrays into a new array named 'newArray'...

array1 = ([[25, 16]])
array2 = ([[11, 2], [13, 4]])
array3 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)

# 12. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2,2,3)
print(reshapedArray)

# 14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
# [[[16 25  2]
#   [11  4 13]]

#  [[ 7 81  5]
#   [ 6 11 12]]]

arrayOne, arraytwo = reshapedArray
var1, var2 = arrayOne
var3, var4 = arraytwo
print(var1, var2, var3, var4)

















[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
[16 25  2] [11  4 13] [ 7 81  5] [ 6 11 12]


In [62]:
# 16. Combined and sort the following arrays into one called 'comboArray' ...

arrayOne = ([10, 11, 12, 13, 14, 15, 16, 17])
arrayTwo = ([20, 21, 22, 23, 24, 25, 26, 27])
arrayThree = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((arrayOne, arrayTwo, arrayThree))
print(comboArray)

# 17. Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
print(comboArray[1])

# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])

# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:13])

# print sec4 - the last 6 elements
print(len(comboArray))
print(comboArray[-6:])


# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[24:-10])

# print sec6 - from #20 every even element to the end
print(comboArray[20::2])

# print sec7 - from the last element moving forward, every 5th element.

everyFifthElement = comboArray[-1::5]
print(everyFifthElement)




[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
11
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24]
24
[2 3 4 5 6 7]
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26]
[4 5 6 7]
[10 15 22 27  4]


In [86]:
import numpy as np
import pandas as pd

# 20.  Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can

ingredients = pd.Series(["flour", "milk", "eggs","spam"], name="ingredients")
quantity = pd.Series(["4", "1", "2", "1"], name="quantity")
unit = pd.Series(["cups", "cup", "large", "can"], name= "unit")
df = pd.concat([ingredients, quantity, unit], axis=1)
print(df)

# 21. Take this data and create a DataFrame named studentData

rawStudentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(rawStudentData)

print(studentData)

# 22. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
desert = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["deserts"] = desertf
print(studentData)

# 23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"f

studentData.sort_values(by = ['Name'], inplace = True)
print(studentData)

studentData.sort_values(by = ['address'], inplace = True)
print(studentData)

# 24. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
cowsGoatData = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

cowsGoatData.to_csv("cows_and_goats.csv")
cowsGoatData = pd.read_csv("cows_and_goats.csv")
print('cows_and_goats.csv')


#25. Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

#Part A
veggieName = pd.Series(["tomato", "cauliflower", "cucumber"], name="vegetable")
quantity = pd.Series(["red", "white", "green",], name="color")
unit = pd.Series(["summer", "winter", "spring",], name= "harvest season")

veggieFrame = pd.concat([veggieName, quantity, unit], axis=1)
veggieFrame.to_csv("veggie_info.csv")
print(veggieFrame)

#Part B
seeds = pd.Series(["yes", "no", "yes"])
veggieFrame["seeded"] = seeds
veggieCopy = veggieFrame.to_csv("veggie_info_copy.csv")
print(veggieCopy)


f



  ingredients quantity   unit
0       flour        4   cups
1        milk        1    cup
2        eggs        2  large
3        spam        1    can
      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Ha